[package]
name = "te-python"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "_trec_eval"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["abi3-py38"] }
te-rust = { path = "../te-rust" }

[features]
default = []
extension-module = ["pyo3/extension-module"]



